serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 9592
  path: /api/idm
loggerConfig:
  outputDir: ./logs/
  outputFile: basicService.log
databaseConfig:
  dbUsername: kanec1
  dbPassword: cs122b
  dbHostname: localhost
  dbPort: 3306
  dbDriver: mysql
  dbName: idmdb
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST
sessionConfig:
  timeout: 600000
  expiration: 1800000